### ISSUE TITLE
Clicks on larger children are canceled 

### ISSUE THREAD

**Issue by lorensr** [fians/Waves#128]
When I use this technique:

http://stackoverflow.com/questions/15611905/making-the-clickable-area-of-in-line-links-bigger-without-affecting-the-layout

and click on a point that is within the `:after` but outside the `.waves-effect` element, the click is canceled (the wave does not occur and the link `href` is not loaded). The desired behavior is for both the click event to occur and for the waves effect to occur, originated at the point on the edge of the `.waves-effect` element that is closest to the click location.

**Comment by hoxxep** [comment]
Codepen: http://codepen.io/anon/pen/QbgXJL

You'll see from this codepen that the `:after` pseudo-element is contained within the `<a>` link. Because the `.waves-effect` element *requires* `overflow:hidden`, the pseudo-element is hidden inside the `<a>` tag.

In the codepen, I've added a workaround using the margin and padding (although this may require `display: inline-block`). This does make the waves-effect overly large unless you reduce the size of the margin and padding I've used.

In the third example, I've wrapped the text in a span, but the .waves-effect will now only be initiated if the span is clicked, otherwise it will just hit the link. Unless you want to manually write some JS to fire a `Waves.ripple()` event when the `.extra` element is clicked.

Note that waves is intended to give visual feedback for a click on a block/button-styled element rather than inline text.

**Comment by lorensr** [comment]
Thank you! My `.waves-effect` is on link that contains an icon, and already has circular padding. I want the `:after` to be larger than the circle that the wave fills. That would be the easiest solution, but I take it that method is not workable, so I will go the 3rd route with `Waves.ripple()`.
