### ISSUE TITLE
Waves doesn't work with new version

### ISSUE THREAD

**Issue by youssefdetovernickr** [fians/Waves#58]
Your new version with the touch-interaction fix isn't working. The waves effect isn't working on my page, but it does with your latest stable release. Code is just the simple example you gave on your own site, your new release just doesn't work on desktop.

**Comment by youssefdetovernickr** [comment]
No fians.. I meant that before it didn't work on only my site, but now it neither works on your own demo site. I don't get any error logs, but clicking results it not doing anything, however when I'm on mobile everything is fine. It worked great when you didn't add the touch events check, a long time ago that was..

**Comment by hoxxep** [comment]
@youssefdetovernickr Are you using a touch screen laptop, because I reckon that could be the issue?

Waves doesn't apply the mouseup/mousedown event listeners when there's a touch device enabled. A mouse click wont register the touch events, so we probably need to bind both touch events.

This assumes that a touch device won't activate mousedown, otherwise we'd have a small issue. Realistically, the worst that could happen is a double-ripple, which would probably look fine anyway since they'd be in the same position and have the same timing; so it would have the same effect as increasing the opacity.

### Old code
```javascript
if ('ontouchstart' in window) {
    i.addEventListener('touchstart', Effect.show, false);
    i.addEventListener('touchend', Effect.hide, false);
    i.addEventListener('touchcancel', Effect.hide, false);
} else {
    i.addEventListener('mousedown', Effect.show, false);
    i.addEventListener('mouseup', Effect.hide, false);
    i.addEventListener('mouseleave', Effect.hide, false);
}
```

### Possible fix?
```javascript
if ('ontouchstart' in window) {
    i.addEventListener('touchstart', Effect.show, false);
    i.addEventListener('touchend', Effect.hide, false);
    i.addEventListener('touchcancel', Effect.hide, false);
}
// always bind mouse events
i.addEventListener('mousedown', Effect.show, false);
i.addEventListener('mouseup', Effect.hide, false);
i.addEventListener('mouseleave', Effect.hide, false);
```

**Comment by youssefdetovernickr** [comment]
@hoxxep I don't got a touch screen laptop.. Just a regular Windows 8.1 desktop (however I do think that touch is somehow activated yeah...) 

Your fix seems the most logical tho.

**Comment by hoxxep** [comment]
Should hopefully be solved on pull request #79 with the delegated touch/mouse handler. This means `v0.6.0` will hopefully be launched within the next week so we can double check that this works on windows touchscreen laptops and some android devices that had issues :smile:

**Comment by youssefdetovernickr** [comment]
Isn't it far more logical to completely get rid of "touchstart", as "mousedown" also works for touch devices?

**Comment by hoxxep** [comment]
`touchstart` responds as soon as the touch occurs, whereas `mousedown` has a 300ms delay *after* the touch is released, and is immediately followed by a `mouseup` event.. In a way yes - but the current solution works fully and looks nicer. For example, clicking a [Snarl](https://hoxxep.github.io/snarl) notification on mobile lets the Waves effect run for 300ms before the click event happens, which looks nicer and feels more responsive.

It could have been a solution, but since it works 100% with touch devices now (as tested on iOS and iOS simulator?) and feels nicer for the user this way we may as well keep it. If we run into deeper and more troublesome issues, we might resort to that - but that would be admitting defeat :wink:

**Comment by youssefdetovernickr** [comment]
Well, it currently works now, only the effect appears twice and it's far too white/dark because of that.

**Comment by youssefdetovernickr** [comment]
Oh yeah something else, you can disable the 300ms thing by adding a meta tag (unsure which atm, I'm on mobile).

**Comment by fians** [comment]
@youssefdetovernickr I just release beta preview for v0.6.0. Please check it out http://fian.my.id/Waves/0.6.0-beta/.

**Comment by youssefdetovernickr** [comment]
Seems ok now.

**Comment by hoxxep** [comment]
Fantastic!
