### ISSUE TITLE
Waves does not work correctly on Windows computers with touchscreen + Chrome

### ISSUE THREAD

**Issue by Dogfalo** [fians/Waves#76]

**Comment by hoxxep** [comment]
As far as I'm aware, this issue should be fixed on v0.6.0-dev; although this hasn't been confirmed yet. This is also a duplicate of issue #58 (although this one is better titled).

If you have a little experience with JS and Git then if you have a touchscreen Windows computer it would be great if you could test it for us?

To clone branch `v0.6.0-dev` do the following inside a new folder.

```bash
git init
git remote add -t v0.6.0-dev -f origin https://github.com/fians/Waves
git checkout v0.6.0-dev
```

If it's too difficult getting node installed on Windows feel free to wait until v0.6 is released and I'll send you a message and ask if you could test that site. Unless @fians wants to upload v0.6.0 onto [fian.my.id/Waves/dev](http://fian.my.id/Waves/dev), which would allow everyone with different devices to test things on the dev version of Waves.

**Comment by Dogfalo** [comment]
Oh great, I didn't know there was a fix. I don't actually have a touchscreen windows computer, but hopefully it will fix issues people have been having in my project.

**Comment by hoxxep** [comment]
You can try download `waves.min.css` and `waves.min.js` from the `dist/` folder in the `v0.6.0-dev` branch and use it in your project? As far as I'm aware it's currently in stable condition, just awaiting new features before we publish it officially. 

If you do decide to use it then let us know if it solves the issues because we haven't been able to test it yet ourselves. Cheers!
