### ISSUE TITLE
Disable Wave effect when you scroll (touch)

### ISSUE THREAD

**Issue by polikin** [fians/Waves#89]
When you scroll down/up, the effect is call everytime you "click -> scroll" over the element. It is possible to disable the effect onScroll?

http://screencast-o-matic.com/u/VAds/waves

**Comment by apolkingg8** [comment]
same issue + 1

**Comment by hoxxep** [comment]
This would be quite difficult to fix, because Waves has to bind touch events. If we had to wait to check whether the user has touched or scrolled, the effect isn't quite as clean. The effect fires before the scroll, so disabling it while the user is scrolling has no impact. In all honesty, it doesn't look overly bad nor impact an application's function.

We could try to use [fastclick](https://github.com/ftlabs/fastclick) and only fire waves on touch-up events if the user hasn't moved the touch more than x number of pixels, but this means that waves can't appear during touch-and-hold events.

I think this depends on which compromise we prefer, and the touch-and-hold is potentially a more important scenario (showing the user is pressing an element), and rippling during touch-scrolling isn't a bad scenario (showing the user has touched/skimmed over an element).

Personally, I think this is a `wontfix` "bug"; the user has touched the element, so like water whether you touch or skim over the surface, it's possible to counter-argue that it should ripple anyway. Does that make sense?

**Comment by polikin** [comment]
Make sense.

**Comment by fians** [comment]
I will try to find a way how to fix this.

**Comment by polikin** [comment]
cool, thanks!

**Comment by danielhickman** [comment]
Just thought I would add, when you drag the wave moves with you in Android (not waves, but Lollipop's effect) The orange box is to protect their phone number because the app never wanted to stay in the same position.
![2015_03_10_20_26_09_1](https://cloud.githubusercontent.com/assets/5341898/6589911/6b1e2aa2-c765-11e4-9aa7-ea5e741ad23e.gif)

**Comment by simonbbyrne** [comment]
This is actually quite confusing for a user when you are scrolling a list. Native user experience does not do this. 
I was considering dealing with this, but the more i used the list in my app, the more annoying it became.

**Comment by lorensr** [comment]
Happening for me too, my use case is a list of checkboxes, and when I scroll down, the wave effect happens. Should only happen on tap/click, not touchdown:

![image](https://cloud.githubusercontent.com/assets/251288/6675712/bf1722d4-cbdf-11e4-857b-ae3144635fd2.png)

**Comment by fians** [comment]
@hoxxep has fix this issue. It solved on Windows Phone (IE), could someone check it on other phones like iOS and Android? Here is the preview: http://fian.my.id/Waves/v0.7.0-dev/

**Comment by hoxxep** [comment]
Works for me on iOS 8. 

Also: apologies for being so stubbornly against the time delay on waves. I realise I was wrong and it still works well with the delay.

**Comment by Cosmitar** [comment]
Works on Android 4.1.2 browser Chrome v 41.0.2272.96

**Comment by polikin** [comment]
Works on Android 4.4 - Chrome v 41.0.2272.96

**Comment by fians** [comment]
I think it's enough. This will fixes will be bundled in v0.7.0 (currently in dev stage).

**Comment by polikin** [comment]
Good job!

**Comment by simonbbyrne** [comment]
Fairplay, thanks!
